language: node_js
node_js:
- node
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: mlNb5h27kBYvPuyRn8jeKKUbaI9PsOhMyqTHimklWJ/pmZPw9sjNJa/2KQxXWpejlJu6RvBnf4maeA3WsRdYCuMHHJFN0w5Y+FPxulRYSlmj2JvVHNHgia/0bop6xHEPyAG5muZsJKhI09c72bd5AFbxlyBGH7Myudf5VFQOSlVXNF04XbDqP1y8EMgkxLK0CFLaez/w0ge2OX4RHMyJP1pZJBvau7CISdfyik8RybdShM6x7dLOpgkwXxuarBSPErWR/dZJYsc+IA7KKGhxKBC98RzKfgQr0Jn5tEfmVm10CRdTX++EyFcp8Nmt7CAQxNkss7jo7mKNthKxbflbsTouGMZc6ySU8+TRh/ay8VjNcJRxdRP06k2SVHEwmROgUtdgwYtrSVZONdOpga9HAWX2Os/2bjfwGioq8KPFefH61BV/gHeSN7UBsXbWihUZIaDPWm+zdTSMfl7Z8EsGmdbV71jIMOc0lnbQbiZoT+txqj7v4dbxWWM5FIHAJnUPIqEyUyZixzonRttwAVR04zIAZjAGuOidfUGDlf3JgVrapOZUDqlo98JLCcv2BgGrwkFJMaqkQSvQMW7b1zv1Pxj9/wfI19jt1nt+iYyrFGdr0A14OPGjG2wrTjPLbcTFYo0cCepn0SWKgcn+DgW8F/OpiKO6XfbvysOxbVUkWk4=
  on:
    tags: true
    repo: softbrix/idre-number-cache
